// Code generated by AROS-project-files/go/repro/mkdefs-aros.py from the AROS SDK; DO NOT EDIT.

//go:build aros && arm64

package runtime

// Library vector offsets: a function is the pointer at base - 8*LVO.
const (
	_LVO_FindTask    = 49  // exec
	_LVO_AllocMem    = 33  // exec
	_LVO_FreeMem     = 35  // exec
	_LVO_Wait        = 53  // exec
	_LVO_Signal      = 54  // exec
	_LVO_AllocSignal = 55  // exec
	_LVO_OpenDevice  = 74  // exec
	_LVO_CloseDevice = 75  // exec
	_LVO_Write       = 8   // dos
	_LVO_Output      = 10  // dos
	_LVO_Delay       = 33  // dos
	_LVO_GetVar      = 151 // dos
	_LVO_GetSysTime  = 11  // timer
	_LVO_GetUpTime   = 12  // timer
)

const (
	_MEMF_ANY            = 0
	_MEMF_CLEAR          = 65536
	_UNIT_MICROHZ        = 0
	_sizeof_timerequest  = 80
	_IORequest_io_Device = 48
	_Task_tc_SPLower     = 104
	_Task_tc_SPUpper     = 112
	_Process_pr_CES      = 488
	_TICKS_PER_SECOND    = 50
)
