// Code generated by AROS-project-files/go/repro/mkdefs-aros.py from the AROS SDK; DO NOT EDIT.

//go:build aros && arm64

package runtime

// Library vector offsets: a function is the pointer at base - 8*LVO.
const (
	_LVO_FindTask           = 49  // exec
	_LVO_AllocMem           = 33  // exec
	_LVO_FreeMem            = 35  // exec
	_LVO_Wait               = 53  // exec
	_LVO_Signal             = 54  // exec
	_LVO_AllocSignal        = 55  // exec
	_LVO_OpenDevice         = 74  // exec
	_LVO_CloseDevice        = 75  // exec
	_LVO_Write              = 8   // dos
	_LVO_Output             = 10  // dos
	_LVO_Delay              = 33  // dos
	_LVO_GetVar             = 151 // dos
	_LVO_GetSysTime         = 11  // timer
	_LVO_GetUpTime          = 12  // timer
	_LVO_SetSignal          = 51  // exec
	_LVO_FreeSignal         = 56  // exec
	_LVO_CreateMsgPort      = 111 // exec
	_LVO_DeleteMsgPort      = 112 // exec
	_LVO_CreateIORequest    = 109 // exec
	_LVO_DeleteIORequest    = 110 // exec
	_LVO_DoIO               = 76  // exec
	_LVO_SendIO             = 77  // exec
	_LVO_AbortIO            = 80  // exec
	_LVO_WaitIO             = 79  // exec
	_LVO_OpenLibrary        = 92  // exec
	_LVO_CloseLibrary       = 69  // exec
	_LVO_OpenResource       = 83  // exec
	_LVO_CurrentDir         = 21  // dos
	_LVO_UnLock             = 15  // dos
	_LVO_OpenLocale         = 26  // locale
	_LVO_CloseLocale        = 7   // locale
	_LVO_HostLib_Open       = 1   // hostlib
	_LVO_HostLib_Close      = 2   // hostlib
	_LVO_HostLib_GetPointer = 3   // hostlib
	_LVO_HostLib_Lock       = 7   // hostlib
	_LVO_HostLib_Unlock     = 8   // hostlib
	_LVO_IoErr              = 22  // dos
)

const (
	_MEMF_ANY              = 0
	_MEMF_CLEAR            = 65536
	_UNIT_MICROHZ          = 0
	_sizeof_timerequest    = 80
	_IORequest_io_Device   = 48
	_Task_tc_SPLower       = 104
	_Task_tc_SPUpper       = 112
	_Task_tc_TrapCode      = 88
	_ExceptionContext_pc   = 256
	_Process_pr_CES        = 488
	_TICKS_PER_SECOND      = 50
	_IORequest_io_Unit     = 56
	_IORequest_io_Command  = 64
	_timerequest_tr_time   = 72
	_TR_ADDREQUEST         = 9
	_MsgPort_mp_SigBit     = 33
	_Task_tc_Flags         = 32
	_TF_STACKCHK           = 16
	_Process_pr_CurrentDir = 344
	_Process_pr_WindowPtr  = 408
	_Process_pr_LocalVars  = 456
	_Locale_loc_GMTOffset  = 112
	_ExceptionContext_x28  = 224
	_ExceptionContext_fp   = 232
	_ExceptionContext_lr   = 240
	_ExceptionContext_sp   = 248
)
