// Code generated by AROS-project-files/go/repro/mkdefs-aros.py from the AROS SDK; DO NOT EDIT.

//go:build aros && arm64

package syscall

// Library vector offsets: a function is the pointer at base - 8*LVO.
const (
	_LVO_FindTask      = 49  // exec
	_LVO_Open          = 5   // dos
	_LVO_Close         = 6   // dos
	_LVO_Read          = 7   // dos
	_LVO_Write         = 8   // dos
	_LVO_Seek          = 11  // dos
	_LVO_SetFileSize   = 76  // dos
	_LVO_Lock          = 14  // dos
	_LVO_UnLock        = 15  // dos
	_LVO_Examine       = 17  // dos
	_LVO_ExNext        = 18  // dos
	_LVO_ExamineFH     = 65  // dos
	_LVO_CreateDir     = 20  // dos
	_LVO_DeleteFile    = 12  // dos
	_LVO_Rename        = 13  // dos
	_LVO_SetProtection = 31  // dos
	_LVO_SetFileDate   = 66  // dos
	_LVO_NameFromLock  = 67  // dos
	_LVO_CurrentDir    = 21  // dos
	_LVO_Fault         = 78  // dos
	_LVO_Input         = 9   // dos
	_LVO_Output        = 10  // dos
	_LVO_GetVar        = 151 // dos
)

// dos error codes (IoErr), as Errno.
const (
	ERROR_NO_FREE_STORE          Errno = 103
	ERROR_BAD_NUMBER             Errno = 115
	ERROR_LINE_TOO_LONG          Errno = 120
	ERROR_OBJECT_IN_USE          Errno = 202
	ERROR_OBJECT_EXISTS          Errno = 203
	ERROR_DIR_NOT_FOUND          Errno = 204
	ERROR_OBJECT_NOT_FOUND       Errno = 205
	ERROR_ACTION_NOT_KNOWN       Errno = 209
	ERROR_INVALID_COMPONENT_NAME Errno = 210
	ERROR_INVALID_LOCK           Errno = 211
	ERROR_OBJECT_WRONG_TYPE      Errno = 212
	ERROR_DISK_WRITE_PROTECTED   Errno = 214
	ERROR_RENAME_ACROSS_DEVICES  Errno = 215
	ERROR_DIRECTORY_NOT_EMPTY    Errno = 216
	ERROR_DEVICE_NOT_MOUNTED     Errno = 218
	ERROR_SEEK_ERROR             Errno = 219
	ERROR_DISK_FULL              Errno = 221
	ERROR_DELETE_PROTECTED       Errno = 222
	ERROR_WRITE_PROTECTED        Errno = 223
	ERROR_READ_PROTECTED         Errno = 224
	ERROR_NO_DISK                Errno = 226
	ERROR_NO_MORE_ENTRIES        Errno = 232
	ERROR_NOT_IMPLEMENTED        Errno = 236
	ERROR_BUFFER_OVERFLOW        Errno = 303
)

const (
	_MODE_OLDFILE                   = 1005
	_MODE_NEWFILE                   = 1006
	_MODE_READWRITE                 = 1004
	_SHARED_LOCK                    = -2
	_EXCLUSIVE_LOCK                 = -1
	_OFFSET_BEGINNING               = -1
	_OFFSET_CURRENT                 = 0
	_OFFSET_END                     = 1
	_FAULT_MAX                      = 82
	_TICKS_PER_SECOND               = 50
	_GVF_GLOBAL_ONLY                = 256
	_GVF_LOCAL_ONLY                 = 512
	_GVF_BINARY_VAR                 = 1024
	_LV_VAR                         = 0
	_LVF_IGNORE                     = 128
	_Process_pr_CES                 = 488
	_Process_pr_CurrentDir          = 344
	_Process_pr_LocalVars           = 456
	_Node_ln_Succ                   = 0
	_Node_ln_Type                   = 16
	_Node_ln_Name                   = 24
	_LocalVar_lv_Flags              = 32
	_sizeof_FileInfoBlock           = 264
	_FileInfoBlock_fib_DirEntryType = 8
	_FileInfoBlock_fib_FileName     = 12
	_FileInfoBlock_fib_Protection   = 120
	_FileInfoBlock_fib_Size         = 128
	_FileInfoBlock_fib_Date         = 136
	_FileInfoBlock_fib_Comment      = 148
	_sizeof_DateStamp               = 12
)
